### PR TITLE
Closes #22 - CountdownView Bug fixes

### LINKED ISSUE #22: Fix countdown getting stuck on 0:00:00 when it is over
It is supposed to change to "Happening now" but does not for some reason.

### PR DESCRIPTION
**Pull request by furkanaskin**
just added post{...} 🤷‍♂  @haroldadmin

### CODE REVIEW

**Comment by haroldadmin** [comment]
Hi @furkanaskin! Really happy to see you contributing.

For the PR, have you been able to manually test your solution? In my experience the countdown doesn't always remain stuck at 0:00:00 after running out, which is what makes this issue hard to debug. I'm curious to hear what is your reasoning behind adding the `post { ... }` block.

**Comment by furkanaskin** [comment]
I tried with your code and it stucked a few time. Then i just added post and tested it again, it seems like resolved but you can try it yourself. Otherwise we must edit return "$dayD:..." With return if(day==0&hour==0...) "Happening now" else "$dayD:..."

**Comment by haroldadmin** [comment]
I'll try this out in a couple of days and let you know what I find. Hopefully I can also add some UI tests to prevent errors like this in the future.

**Comment by haroldadmin** [comment]
@furkanaskin Your solution makes sense. A countdown timer runs on a background thread, which seems to be the causing the stuck textview issue. Thanks for fixing this!

**Pull request merged**
